### ISSUE TITLE
News Section do not scrape

### ISSUE THREAD

**Issue by taleeb35** [SneakyBobito/google-url#9]
I used your library for scrapping.When we search on Google there is always a news section against all search but your library did not fetch the news section.

Any Help?

Thanks

**Comment by SneakyBobito** [comment]
Hello, 

Sure I can help.

Can you tell me more about this section ? What kind of section is it ? (we have to make sure we use the same terminology)

**Comment by taleeb35** [comment]
When we search about some company or organization on Google so there is always a "In the News" section on the result page.In  "www.google.com.au" I searched "telstra" using your library and it return me title of every link of the result page except "In the News" title.

Is it Clear Now?

**Comment by SneakyBobito** [comment]
I see the "in the news", thanks for the information.

Indeed this is not parsed. This kind of result is different of the normal ones.

Actually there are still a lot of results like this one that the library doesn't still handle.

I have to search for the best solution that i can bring to you to keep best flexibility and functionality. I have to make it global and extensible for future uses. 

Please let me a few hours to think about the best solution, because it is very important for what the library will look in its future.

If I don't find a solution soon, I still can give you a way to deal with it. Please keep looking for my next answer !

**Comment by taleeb35** [comment]
Ok I am waiting.Thanks a lot for your quick response.

**Comment by SneakyBobito** [comment]
@taleeb35 I have refactored the page parser. This is a big change in the library because it will allow to implement every kind of results and to read them on a more easy way.

This will be flagged as a v2 because there will be a few compatibility errors. I still have to clean a few things and to write a basic guide on how it should be used.

The good news is that the "in the news" box is well parsed now.

Can you still leave me a few time until I make everything ok ? I will try to make it in the night and make it ok for tomorow (it's alsmost 19h here)

**Comment by taleeb35** [comment]
Take your time.

**Comment by taleeb35** [comment]
When will you update the project?

**Comment by SneakyBobito** [comment]
Sorry I have got delays.

Everything is not ready yet. I still have to write the doc, and the tests are not ready yet.


You can already use it (but remember that it's still as a "beta"). Just tell composer track the branch ``dev-v2``  (``"sneakybobito/google-url": "dev-dev-v2"`` with the double "dev-" in front). 

You can check the examples at : http://google-url.laemon.com/#/  but the doc is not complet yet. And right now only ``classical results`` and ``inTheNewsGroup results`` are parsed. I'm implementing the others right now.

**Comment by SneakyBobito** [comment]
I'm closing the issue, if you have any problem feel free to open it again

**Comment by taleeb35** [comment]
"In the News" Section will parse now or not?
